---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "nexus-storage"
  namespace: "default"
  labels:
    app: "nexus-storage"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "nexus-storage"
  template:
    metadata:
      labels:
        app: "nexus-storage"
    spec:
      containers:
      - name: "nexus-osama"
        image: "gcr.io/nexuskubernetes/nexus-osama:0.1"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
  name: "nexus-storage-hpa"
  namespace: "default"
  labels:
    app: "nexus-storage"
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: "nexus-storage"
    apiVersion: "apps/v1beta1"
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: 80
